# Generated by Django 4.2.7 on 2026-03-09 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('CCTV', 'CCTV'), ('Telecom', 'Telecom'), ('Signal Boosting', 'Signal Boosting'), ('Networking', 'Networking'), ('Fiber Optic', 'Fiber Optic'), ('Other', 'Other')], default='CCTV', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GallerySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Setting',
            },
        ),
    ]
